boxes:
    python2.6
    python2.7

install:
    # based on http://www.howtoforge.com/vboxheadless-running-virtual-machines-with-virtualbox-4.1-on-a-headless-ubuntu-11.10-server
    - sudo wget http://mac4deb.googlepages.com/addrepo -O /usr/bin/addrepo
    - sudo chmod +x /usr/bin/addrepo
    - addrepo deb http://download.virtualbox.org/virtualbox/debian oneiric contrib
    - wget -q http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | sudo apt-key add -

    - sudo aptitude update
    - sudo aptitude install -y virtualbox-4.2
    - wget http://download.virtualbox.org/virtualbox/4.2.0/Oracle_VM_VirtualBox_Extension_Pack-4.2.0-80737.vbox-extpack && sudo VBoxManage extpack install Oracle_VM_VirtualBox_Extension_Pack-4.2.0-80737.vbox-extpack && rm Oracle_VM_VirtualBox_Extension_Pack-4.2.0-80737.vbox-extpack
    - sudo adduser `whoami` vboxusers

    - VBoxManage --help

    # weird travis-ci python paths
    - export PYTHONPATH=$PYTHONPATH:/usr/lib/pymodules/python2.7/
    - export PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages
    - export PYTHONPATH=$PYTHONPATH:/usr/lib/pyshared/python2.7/
    - export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/site-packages/

    # install python requirements
    - pip install -r python_requirements.txt --use-mirrors

script:
    # weird travis-ci python paths
    - export PYTHONPATH=$PYTHONPATH:/usr/lib/pymodules/python2.7/
    - export PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages
    - export PYTHONPATH=$PYTHONPATH:/usr/lib/pyshared/python2.7/
    - export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/site-packages/

    # finally run tests
    - make ci-test

